steps:
  - label: ":chart_with_upwards_trend: Run Tracy workload (x86_64)"
    agents:
      queue: "juliaecosystem"
      os: "linux"
      arch: "x86_64"
    plugins:
      - JuliaCI/julia#v1:
          version: 1
      # Use the current directory as the plugin source, so we're testing this version of `tracy`
      - "./.buildkite/plugins/tracy":
          trace: "test.tracy"
    commands: |
      julia --project=test -e 'import Pkg; Pkg.instantiate()'
      julia --project=test test/runtests.jl
    artifacts:
      - test.tracy
      - capture_agent.log
    # Don't waste queue time if we run into some kind of hang
    timeout_in_minutes: 5

  - label: ":chart_with_upwards_trend: Run Tracy workload (aarch64)"
    agents:
      queue: "juliaecosystem"
      os: "linux"
      arch: "aarch64"
    plugins:
      - JuliaCI/julia#v1:
          version: 1
      # Use the current directory as the plugin source, so we're testing this version of `tracy`
      - "./.buildkite/plugins/tracy":
          trace: "test.tracy"
    commands: |
      julia --project=test -e 'import Pkg; Pkg.instantiate()'
      julia --project=test test/runtests.jl
    artifacts:
      - test.tracy
      - capture_agent.log
    # Don't waste queue time if we run into some kind of hang
    timeout_in_minutes: 5
    soft_fail: true
